apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{ .Values.Agent.ComponentName }}
    app: {{template "name" .}}
spec:
  replicas: 1 # Should only have 1 per cluster
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        component: {{.Values.Agent.ComponentName}}
        app: {{template "name" .}}
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- else }}
      nodeSelector:
        role: master
    {{- end }}
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Exists
          effect: NoSchedule
      {{- if .Values.Agent.RepoSecretName }}
      imagePullSecrets:
      # This must exist within the namespace in which you plan to deploy
      - name: {{ .Values.Agent.RepoSecretName | quote }}
      {{- end }}
      containers:
      - name: {{ template "fullname" . }}
        image: "{{.Values.Agent.Image}}:{{.Values.Agent.ImageTag}}"
        imagePullPolicy: "{{.Values.Agent.ImagePullPolicy}}"
        env:
        - name: KUBEVIZ_TOKEN
          value: {{ .Values.Agent.ApiKey }}
        - name: "KUBEVIZ_SERVER_ADDRESS"
          value: "{{ .Values.Agent.ApiEndpoint }}"
        - name: "AWS_ACCESS_KEY_ID"
          value: "{{ .Values.Agent.AwsAccessKey }}"
        - name: "AWS_SECRET_ACCESS_KEY"
          value: "{{ .Values.Agent.AwsSecretKey }}"
        {{- if .Values.Agent.ClusterName }}
        - name: KUBEVIZ_CLUSTER_NAME
          value: {{ .Values.Agent.ClusterName }}
        {{- end }}
